/**
 * Cardio sets survive the round trip — FR-CAR-02, FR-CAR-03.
 *
 * This suite exists because they did not. `addSet` never wrote `duration_secs`
 * or `distance_m`, and `updateSet` never patched them: the Zod schema accepted
 * both, the insert dropped both, and the response came back 200 with the
 * fields null. Every treadmill entry looked saved and was gone.
 *
 * The lesson worth encoding is that a field is only real when it has been read
 * back out of the database — validating it and returning 200 proves nothing.
 */
import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, beforeEach, expect, it } from 'vitest';
import type { ExerciseSummary, WorkoutDetail } from '@fi/shared';
import {
  client,
  closeTestContext,
  createTestContext,
  describeIntegration,
  first,
  registerUser,
  seedCatalogue,
  truncateAll,
  type TestClient,
  type TestContext,
} from './helpers/harness';

describeIntegration('cardio sets', () => {
  let ctx: TestContext;
  let api: TestClient;
  let treadmillId: string;
  let workoutId: string;
  let weId: string;

  beforeAll(async () => {
    ctx = await createTestContext();
    await truncateAll(ctx.database);
    await seedCatalogue(ctx);
  });
  afterAll(async () => {
    await closeTestContext(ctx);
  });

  beforeEach(async () => {
    api = client(ctx.app, await registerUser(ctx.app));

    const list = await api.get('/api/v1/exercises?q=Treadmill&limit=1');
    const treadmill = first(list.json<{ items: ExerciseSummary[] }>().items, 'treadmill');
    treadmillId = treadmill.id;
    // If this ever fails the catalogue changed, and the cardio UI is picked by
    // exactly this field — a treadmill typed 'strength' shows kg and reps.
    expect(treadmill.kind).toBe('cardio');

    workoutId = randomUUID();
    await api.post('/api/v1/workouts', { id: workoutId, startedAt: '2026-09-03T09:00:00Z' });
    weId = randomUUID();
    await api.post(`/api/v1/workouts/${workoutId}/exercises`, {
      id: weId,
      exerciseId: treadmillId,
    });
  });

  /** The one set of the one exercise, straight from a fresh read. */
  const readBackSet = async () => {
    const detail = (await api.get(`/api/v1/workouts/${workoutId}`)).json<WorkoutDetail>();
    return first(first(detail.exercises, 'exercise').sets, 'set');
  };

  it('stores duration and distance given when the set is created', async () => {
    await api.post(`/api/v1/workouts/${workoutId}/exercises/${weId}/sets`, {
      id: randomUUID(),
      durationSecs: 1800,
      distanceM: 5000,
      isCompleted: true,
    });

    // Read back through a separate request: the POST response is generated by
    // the same call that wrote, so it can agree with a write that did nothing.
    const set = await readBackSet();
    expect(set.durationSecs).toBe(1800);
    expect(set.distanceM).toBe(5000);
  });

  it('stores duration and distance patched onto an empty set', async () => {
    // This is what the app actually does: the row is added blank when the
    // exercise is picked, then each field commits on blur.
    const setId = randomUUID();
    await api.post(`/api/v1/workouts/${workoutId}/exercises/${weId}/sets`, { id: setId });

    await api.patch(`/api/v1/sets/${setId}`, { durationSecs: 1200 });
    await api.patch(`/api/v1/sets/${setId}`, { distanceM: 3500 });

    const set = await readBackSet();
    expect(set.durationSecs).toBe(1200);
    expect(set.distanceM).toBe(3500);
  });

  it('keeps duration when only distance is patched', async () => {
    const setId = randomUUID();
    await api.post(`/api/v1/workouts/${workoutId}/exercises/${weId}/sets`, {
      id: setId,
      durationSecs: 1200,
    });
    await api.patch(`/api/v1/sets/${setId}`, { distanceM: 3500 });

    const set = await readBackSet();
    expect(set.durationSecs).toBe(1200);
  });

  it('lets a field be cleared back to nothing', async () => {
    const setId = randomUUID();
    await api.post(`/api/v1/workouts/${workoutId}/exercises/${weId}/sets`, {
      id: setId,
      durationSecs: 1200,
      distanceM: 3500,
    });
    await api.patch(`/api/v1/sets/${setId}`, { distanceM: null });

    const set = await readBackSet();
    expect(set.distanceM).toBeNull();
    expect(set.durationSecs).toBe(1200);
  });

  it('accepts a duration with no distance, and a distance with no duration', async () => {
    // "20 minutes on the bike" and "5 km" are both complete logs.
    const timeOnly = randomUUID();
    const distanceOnly = randomUUID();
    await api.post(`/api/v1/workouts/${workoutId}/exercises/${weId}/sets`, {
      id: timeOnly,
      durationSecs: 1200,
    });
    await api.post(`/api/v1/workouts/${workoutId}/exercises/${weId}/sets`, {
      id: distanceOnly,
      distanceM: 5000,
    });

    const detail = (await api.get(`/api/v1/workouts/${workoutId}`)).json<WorkoutDetail>();
    const sets = first(detail.exercises, 'exercise').sets;
    expect(sets.find((set) => set.id === timeOnly)?.distanceM).toBeNull();
    expect(sets.find((set) => set.id === distanceOnly)?.durationSecs).toBe(null);
    expect(sets.find((set) => set.id === distanceOnly)?.distanceM).toBe(5000);
  });

  it('survives completing the workout, which is when the numbers get used', async () => {
    await api.post(`/api/v1/workouts/${workoutId}/exercises/${weId}/sets`, {
      id: randomUUID(),
      durationSecs: 1800,
      distanceM: 5000,
      isCompleted: true,
    });
    const completed = await api.post(`/api/v1/workouts/${workoutId}/complete`, {
      completedAt: '2026-09-03T09:35:00Z',
    });
    expect(completed.statusCode).toBe(200);

    const set = await readBackSet();
    expect(set.durationSecs).toBe(1800);
    expect(set.distanceM).toBe(5000);
  });

  it('refuses a duration longer than a day', async () => {
    const response = await api.post(`/api/v1/workouts/${workoutId}/exercises/${weId}/sets`, {
      id: randomUUID(),
      durationSecs: 90_000,
    });
    // Rejected by the schema, so the DB CHECK is never reached — a 400, not a 500.
    expect(response.statusCode).toBe(400);
  });
});
