/**
 * Primitive schemas every other schema is built from.
 *
 * BRD §10.2: weights travel as numeric strings so no float ever touches a
 * load; timestamps are ISO 8601 with an offset; IDs are UUIDs generated by the
 * client for offline-created entities (NFR-R-04).
 */
import { z } from 'zod';

export const uuidSchema = z.uuid();

/**
 * A weight or volume on the wire. Accepts a number for client convenience and
 * normalises to a string, so the API only ever sees one representation.
 */
export const decimalStringSchema = z
  .union([z.string(), z.number()])
  .transform((value, ctx) => {
    const text = typeof value === 'number' ? String(value) : value.trim();
    if (!/^-?\d{1,10}(\.\d{1,4})?$/.test(text)) {
      ctx.issues.push({ code: 'custom', message: 'Expected a decimal value', input: value });
      return z.NEVER;
    }
    return text;
  })
  .describe('Decimal value as a string, in kilograms where it is a weight');

export const positiveDecimalStringSchema = decimalStringSchema.refine(
  (value) => !value.startsWith('-'),
  { message: 'Must not be negative' },
);

export const isoDateTimeSchema = z.iso.datetime({ offset: true });
export const isoDateSchema = z.iso.date();

/** Free-text the user typed. Trimmed, bounded, and never empty when required. */
export const shortTextSchema = z.string().trim().min(1).max(120);
export const noteTextSchema = z.string().trim().max(2000);
export const slugSchema = z
  .string()
  .trim()
  .min(1)
  .max(80)
  .regex(/^[a-z0-9]+(-[a-z0-9]+)*$/, 'Must be a lowercase hyphenated slug');

/**
 * A cardio effort's duration, in whole seconds.
 *
 * Capped at 24 hours: anything longer is a typo or a forgotten stopwatch, and
 * an unbounded value would let one set distort every total that includes it.
 */
export const durationSecsSchema = z.number().int().min(0).max(86_400, 'That is longer than a day');

/**
 * A cardio effort's distance, in whole metres.
 *
 * Capped at 1,000 km for the same reason. Metres rather than kilometres so the
 * stored value is an integer — a 5.25 km run is 5250, with no decimal to round.
 */
export const distanceMetresSchema = z
  .number()
  .int()
  .min(0)
  .max(1_000_000, 'That is further than anyone runs in a session');

export const positionSchema = z.number().int().min(0).max(999);
export const repsSchema = z.number().int().min(0).max(1000);
export const restSecsSchema = z.number().int().min(0).max(3600);

/** FR-WK-04: RPE is 1–10 in half steps. */
export const rpeSchema = z
  .number()
  .min(1)
  .max(10)
  .refine((value) => Number.isInteger(value * 2), { message: 'RPE moves in 0.5 steps' });

/** BRD §10.2: opaque cursor pagination, default 20, max 100. */
export const paginationSchema = z.object({
  cursor: z.string().max(500).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
});
export type Pagination = z.infer<typeof paginationSchema>;

export function pageSchema<T extends z.ZodType>(item: T) {
  return z.object({
    items: z.array(item),
    nextCursor: z.string().nullable(),
  });
}

export type Page<T> = { items: T[]; nextCursor: string | null };
