-- A form analysis belongs to a SET, not to an exercise.
--
-- cv_analyses has linked to workout_exercise_id since the initial schema,
-- which was the right grain for "a video of my bench press". It is the wrong
-- grain for what is being built: the analysis produces a rep count, a per-rep
-- velocity and a velocity loss across the set, and all three are properties of
-- ONE set. Two videos of the same exercise in a session would otherwise be
-- indistinguishable.
--
-- The old column stays. It is still the cheap way to ask "every analysis for
-- this exercise today" without joining through workout_sets.
--
-- ON DELETE SET NULL rather than CASCADE: deleting a set should not silently
-- destroy a video someone recorded. It does leave a row pointing at nothing,
-- so the R2 object is reclaimed by the bucket's lifecycle rule (ADR 0005:
-- expire user video after 90 days) rather than by a foreign key. That
-- dependency is real — without the lifecycle rule, orphans accumulate and
-- nothing in the database knows they exist.
--
-- 'awaiting_upload' is the state between the row being created — which is what
-- issues the reference id — and the video arriving.
--
-- NOTE FOR THE NEXT PERSON: do not add a migration that USES this new enum
-- value. Postgres refuses with 55P04, "new enum values must be committed
-- before they can be used", and splitting it into a separate migration file
-- does NOT help — Drizzle runs all pending migrations in one transaction. I
-- tried that; the test suite caught it. The column default is therefore left
-- as 'queued', which is harmless because analysis-service always states the
-- status explicitly on insert.
--
-- Generated by `pnpm db:generate` and read line by line: four statements, all
-- additive, no drops.

ALTER TYPE "public"."analysis_status" ADD VALUE 'awaiting_upload' BEFORE 'queued';--> statement-breakpoint
ALTER TABLE "cv_analyses" ADD COLUMN "workout_set_id" uuid;--> statement-breakpoint
ALTER TABLE "cv_analyses" ADD CONSTRAINT "cv_analyses_workout_set_id_workout_sets_id_fk" FOREIGN KEY ("workout_set_id") REFERENCES "public"."workout_sets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_cv_set" ON "cv_analyses" USING btree ("workout_set_id","created_at" DESC NULLS LAST);
