-- Consent for video and form analysis (FR-VID-01).
--
-- A TIMESTAMP, not a boolean. "They agreed" is worth very little without
-- "when": if the wording of the ask changes, the date is the only way to tell
-- who agreed to which version of it.
--
-- NULL means never asked, or refused. The API refuses to issue an upload
-- target while it is null, which is what makes the privacy policy's claim —
-- "it stays off until you agree to it in the app" — enforced rather than
-- asserted.
--
-- Nullable with no default and no backfill, deliberately. Every existing
-- account has NOT consented to being recorded, and defaulting anyone into it
-- would be the exact failure the leaderboard reconsent in 0009 existed to
-- correct.
--
-- Generated by `pnpm db:generate`, read: one additive column, no drops.

ALTER TABLE "user_profiles" ADD COLUMN "video_consent_at" timestamp with time zone;
